[package]
name = "dofus-craft"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "dofus_craft_lib"
crate-type = [
  "lib",
  "cdylib",
  "staticlib"
]

[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }

[dependencies]
tauri = { version = "2.0.0-rc", features = [ "macos-private-api" ] }
tauri-plugin-process = "2.0.0-rc"
tauri-plugin-os = "2.0.0-rc"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
